ARDUINO_DIR = /usr/share/arduino
Arduino_PORT = /dev/arduino

USR_LIB_PATH = /usr/share/arduino/libraries

#ARCHITECTURE = avr
BOARD_TAG = nano328
#BOARD_SUB = Atmega168

include /usr/share/arduino/Arduino.mk

# make show_boards will show you all the board tags you can use